import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Copy the CSS source to the plugin's styles.css on every build.
function copyStyles() {
  try {
    fs.copyFileSync("src/styles.css", "styles.css");
  } catch (e) {
    console.error("Failed to copy styles.css", e);
  }
}

const stylesPlugin = {
  name: "copy-styles",
  setup(build) {
    build.onEnd(() => copyStyles());
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // Optional native add-ons that `ws` requires lazily; not needed at runtime.
    "bufferutil",
    "utf-8-validate",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2020",
  // Bundle for the Node-enabled Electron renderer Obsidian runs in. This is
  // required so node-only deps (ws) resolve to their real implementation rather
  // than the "browser" shim that throws. DOM APIs remain available at runtime.
  platform: "node",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [stylesPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
